# fly.toml app configuration file generated for display-blog on 2023-07-20T10:29:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "display-blog"
primary_region = "cdg"

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
